# Generated by Django 3.2.25 on 2024-04-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='enter_pounds_to_transfer',
            new_name='enter_money_to_transfer',
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='currency',
            field=models.CharField(default='£', max_length=1),
        ),
    ]
