# Generated by Django 3.2.25 on 2024-04-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_auto_20240404_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='money',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='moneytransfer',
            name='enter_money_to_transfer',
            field=models.FloatField(),
        ),
    ]
