# Generated by Django 3.2.25 on 2024-04-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_auto_20240405_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='money',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=14),
        ),
        migrations.AlterField(
            model_name='moneytransfer',
            name='enter_money_to_transfer',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
